### ISSUE TITLE
New name for the project

### ISSUE THREAD

**Issue by rsdy** [ingraind/ingraind#304]
While transferring the project to CNCF, due to trademark issues, we need a new name.

If you have any good ideas for a name going forward, please comment in this thread, and using the :+1: symbol we can count the votes to choose the best name!

**Comment by rsdy** [comment]
I'll start: milligram, which is approximately [64 grains](https://en.wikipedia.org/wiki/Grain_(unit))

**Comment by rhdxmr** [comment]
Do you mean that changing the name of project which is super project of ingraind and redbpf?

**Comment by rhdxmr** [comment]
Or do you mean the name of products? ingraind application and redbpf library?

**Comment by rsdy** [comment]
This is specifically for the `ingraind` application and the umbrella project, as they are trademarked. I don't think we need to rename redbpf.

**Comment by ggPeti** [comment]
Secmocap - the project is like a motion capture suit for application security.

**Comment by rhdxmr** [comment]
I focused on kinds of grains of which names are rarely used. 
My suggestions are...
- `redgram`: `red` from redBPF + `gram` from milligram. it also means pigeon pea.
-  `adlay`: a kind of grain
- `buckwheat`: a kind of grain that I like
- `einkorn`
- `fonio`
- `freekeh`

**Comment by rsdy** [comment]
I like fonio, because it has IO in it :)

**Comment by rhdxmr** [comment]
Haha. Don't you like `red`?
I like fonio too because it is easy to say.

**Comment by rhdxmr** [comment]
I found some words ending with `io`

pistachio
arborio
myrio
intaglio
helio
hagio
elepaio

**Comment by rsdy** [comment]
I think it's time to say that we've decided to go with fonio as the new name for the project. I'm happy to close the issue and look into how transitioning to the name should be done!
